#!/bin/bash

echo "🔧 Starting BonaPic environment bootstrap..."
BASE_DIR=$(pwd)

# --- [1] Folders to create ---
FOLDERS=(
  "cli"
  "data"
  "docs"
  "lib"
  "src/core"
  "src/modules"
  "src/services"
  "src/orphanage"
  "src/sync"
  "src/templates"
  "src/tests"
  "src/utils"
)

for folder in "${FOLDERS[@]}"; do
  if [ ! -d "$folder" ]; then
    mkdir -p "$folder"
    echo "📁 Created folder: $folder"
  fi
done

# --- [2] Base files to create ---
touch_if_missing() {
  local file=$1
  local content=$2
  if [ ! -f "$file" ]; then
    echo -e "$content" > "$file"
    echo "📝 Created file: $file"
  fi
}

touch_if_missing ".env" "# BonaPic Environment Variables\nGAS_PROJECT_ID=\nDEV_MODE=true"
touch_if_missing ".env.template" "# Template for team use\nGAS_PROJECT_ID=__your_project_id__\nDEV_MODE=true"
touch_if_missing ".gitignore" "# Ignore sensitive and generated files\n.env\nnode_modules/\n.DS_Store"
touch_if_missing ".eslintrc.json" '{\n  "env": { "es6": true },\n  "extends": "eslint:recommended",\n  "rules": { "semi": ["error", "always"] }\n}'
touch_if_missing "README.md" "# BonaPic Platform\n\nGenerated by init-env.sh"
touch_if_missing "src/core/envConfig.gs" 'function getEnv(key) {\n  const env = PropertiesService.getScriptProperties().getProperty(key);\n  if (!env) throw new Error(`Missing env: ${key}`);\n  return env;\n}'

# --- [3] Placeholders for empty folders ---
for folder in "${FOLDERS[@]}"; do
  if [ -d "$folder" ] && [ -z "$(ls -A $folder)" ]; then
    echo "# Placeholder – $folder" > "$folder/.keep"
    echo "➕ Added placeholder in empty folder: $folder"
  fi
done

# --- [4] Done ---
echo "✅ Environment setup complete."
